import SignIn from '@/components/signin'
import { getServerSession } from 'next-auth'
import Head from 'next/head'
import { authOptions } from './api/auth/[...nextauth]'

export default function Home({ session }) {
  console.log(session);

  return (
    <>
      <Head>
        <title>Simple Social</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='grid h-screen place-items-center'>
          <div className='min-w-fit grid'>
            <h1 className='text-2xl'>Simple Social</h1>
            <div className='justify-self-center'>
              <SignIn session={session}/>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps(ctx: any) {
  return {
    props: {
        session: await getServerSession(ctx.req, ctx.res, authOptions)
    }
  }
}